apiVersion: v1
kind: Service
metadata:
  name: sample-app-backend-service
spec:
  type: ClusterIP
  selector:
    app: sample-app-backend-pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
