name: Prettier Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npm run format:check

      # - name: Run Prettier (fix formatting)
      #   if: failure()
      #   run: npm run format:fix
